### ISSUE TITLE
Guidance/Possible Feature Request: Check event validity without executing?

### ISSUE THREAD

**Issue by bobziuchkovski** [fgoujeon/fgfsm#2]
Hi, I've been looking at the various C++ FSM libraries and came across maki. The implementation looks pretty clean and it appears you're actively developing/maintaining it.

However, I have a use case that I can't seem to satisfy with maki's current API or that of any of the other FSM libraries I've looked at: constructing the set of valid event types against the machine's current state. Or for that matter, checking validity of a **single** event against the machine's current state without executing it.

All of the FSM libraries I've looked at, maki included, seem to force you to execute each event, rather than inspect the validity of the event or construct a set of valid events for the machine state. For my use case (a digital board game), I need to construct the set of valid events (moves) for the AI algorithm to evaluate/score, and would also like to tap into that as part of the UI. If I can construct a potential event (move) from the UI, such as "play card X" for each given card in a player's hand, and evaluate with the machine if that's a _valid_ event/move given the machine's state/guards, then I can update the UI to indicate whether that's an action the player can take at any given moment. Since I'm just updating UI elements to indicate actions the player can take, I don't actually want to _execute_ the move until the player initiates it.

Anyway, I'm wondering if I'm missing something in maki's API (or for that matter any of the other C++ FSM's you've looked at), or if that's just not something people do with FSMs?

Any guidance you have would be tremendously appreciated. Thanks!

**Comment by fgoujeon** [comment]
Hi Bob,

That's an interesting use case you have here! And your solution seems pretty smart.

So you'd like something like this?

```
template<class Event>
bool machine::would_cause_state_transition();
```

I don't know any FSM library, including mine, that implements such a feature. But this should be doable!

Be aware that I'm in the middle of a big breaking change (see the 'pass-callables-to-conf' branch). I hope you haven't written too much code with the current API.

**Comment by bobziuchkovski** [comment]
```
template<class Event>
bool machine::would_cause_state_transition();
```
Exactly! If that's something you'd be open to exposing in the API, it would be immensely useful for me!

> Be aware that I'm in the middle of a big breaking change (see the 'pass-callables-to-conf' branch). I hope you haven't written too much code with the current API.

No problem! I saw the note about the API not being stable yet. 😄

**Comment by fgoujeon** [comment]
Sure :). It would be an interesting feature for many cases.

**Comment by bobziuchkovski** [comment]
I guess it would probably be more like the following since I'd want to make sure the guards were evaluated as well:

```
template<class Event>
bool machine::would_cause_state_transition(const Event &e) const;
```

But yeah, thanks for being flexible/open to that! I'm not sure I'm familiar enough with maki's internals yet to contribute that change, but maybe I can help contribute some documentation in other areas to help instead. 😄

**Comment by fgoujeon** [comment]
Here is the solution I foresee:

1. changing `machine::process_event_now(const Event&)` so that it returns a boolean indicating whether any state transition or any action call happened;
2. adding a `machine::process_event_now_dry(const Event&) const` that would behave like `machine::process_event_now(const Event&)` (particularly the returning-a-boolean part), except that no transition or action call actually happen.

The first step is fast and easy. The second one is more tedious because it would require to carry some sort of `bool Dry` template argument across most of the library, but it shouldn't be that complicated.

It's not the right time to do anything more than thinking about a solution, but as soon as I finalize the current API change, we could work on this together. Would you be able to write a test case?

**Comment by bobziuchkovski** [comment]
> It's not the right time to do anything more than thinking about a solution, but as soon as I finalize the current API change, we could work on this together. Would you be able to write a test case?

Absolutely!

**Comment by bobziuchkovski** [comment]
Should I write the test cases against current main or against the pass-callables-to-confs branch?

**Comment by fgoujeon** [comment]
The second one, please. Thank you!

**Comment by bobziuchkovski** [comment]
Posted as https://github.com/fgoujeon/maki/pull/3

**Comment by fgoujeon** [comment]
I'm sorry Bob, I wasn't aware you wanted two distinct functions.

To make it clear: `process_event_now_dry` was just a more correct name than that `would_cause_state_transition` I first mentioned.

Do you actually need these two variants?

**Comment by bobziuchkovski** [comment]
Nope, I thought that was something you were proposing. Hah, I'll drop those two commits.

**Comment by fgoujeon** [comment]
Thank you for this suggestion and for your help, @bobziuchkovski!

**Comment by bobziuchkovski** [comment]
> Thank you for this suggestion and for your help, @bobziuchkovski!

Thanks for adding! I'm looking forward to using it. 😄
